pipeline:
  name: Terraform Secret Manager Issue
  identifier: Terraform_Secret_Manager_Issue
  tags: {}
  projectIdentifier: Keshav_Test_Project
  orgIdentifier: Keshav_Test_Org
  stages:
    - stage:
        name: TF
        identifier: TF
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Clone
                  identifier: Clone
                  spec:
                    connectorRef: git_conn_keshav
                    repoName: manifests
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Init
                  identifier: Init
                  spec:
                    connectorRef: DockerRegistryConnector
                    image: hashicorp/terraform:1.11.4
                    shell: Sh
                    command: |-
                      cd /harness/manifests/terraform/secret-manager-issue
                      echo "Terraform Execution starts"
                      ls -l

                      terraform init -reconfigure \
                        -backend-config="access_key=<+pipeline.variables.AWS_ACCESS_KEY>" \
                        -backend-config="secret_key=<+pipeline.variables.AWS_SECRET_KEY>"
              - step:
                  type: Run
                  name: Plan
                  identifier: Plan
                  spec:
                    connectorRef: DockerRegistryConnector
                    image: hashicorp/terraform:1.11.4
                    shell: Sh
                    command: |-
                      cd /harness/manifests/terraform/secret-manager-issue

                      terraform plan \
                        -var=harness_account_id=px7xd_BFRCi-pfWPYXVjvw \
                        -var=harness_api_key=<+pipeline.variables.apiKey> \
                        -var-file=./terraform.tfvars
                  when:
                    stageStatus: Success
                    condition: "false"
              - step:
                  type: Run
                  name: Apply
                  identifier: Apply
                  spec:
                    connectorRef: DockerRegistryConnector
                    image: hashicorp/terraform:1.11.4
                    shell: Sh
                    command: |-
                      cd /harness/manifests/terraform/secret-manager-issue

                      terraform apply -auto-approve \
                        -var=harness_account_id=zEaak-FLS425IEO7OLzMUg \
                        -var=harness_api_key=<+pipeline.variables.apiKey> \
                        -var-file=./terraform.tfvars
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: My_Rancher_Cluster
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        delegateSelectors:
          - kubernetes-delegate
  variables:
    - name: apiKey
      type: Secret
      description: ""
      required: false
      value: apiKey
    - name: AWS_SECRET_KEY
      type: Secret
      description: ""
      required: false
      value: AWS_SECRET_KEY
    - name: AWS_ACCESS_KEY
      type: Secret
      description: ""
      required: false
      value: AWS_ACCESS_KEY
  delegateSelectors:
    - kubernetes-delegate
